### ISSUE TITLE
Bug: 机器人初始化时获取tenant_access_token报错

### ISSUE THREAD

**Issue by moonstoneG** [nonebot/adapter-feishu#45]
03-31 14:04:15 [ERROR] logging | Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\nonebot2\TeamCityBot\.venv\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\Admin\Desktop\nonebot2\TeamCityBot\.venv\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Admin\Desktop\nonebot2\TeamCityBot\.venv\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\Admin\Desktop\nonebot2\TeamCityBot\.venv\Lib\site-packages\nonebot\adapters\feishu\adapter.py", line 72, in _
    "Authorization": f"Bearer {await self._fetch_tenant_access_token(bot_config)}"
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\nonebot2\TeamCityBot\.venv\Lib\site-packages\nonebot\adapters\feishu\adapter.py", line 136, in _fetch_tenant_access_token
    expire = result["expire"]
             ~~~~~~^^^^^^^^^^
KeyError: 'expire'

03-31 14:04:15 [ERROR] logging | Application startup failed. Exiting.

**Comment by ExerciseBook** [comment]
补充：

直接调用这个接口是有返回值的
https://open.feishu.cn/document/ukTMukTMukTM/ukDNz4SO0MjL5QzM/auth-v3/auth/tenant_access_token_internal 
```
{
  "code": 0,
  "expire": 4567,
  "msg": "ok",
  "tenant_access_token": "内容削除"
}
```

**Comment by StarHeartHunt** [comment]
在自建应用上没有复现这个问题，商店应用暂时未适配
